### ISSUE TITLE
Shouldn't look at children for this.check

### ISSUE THREAD

**Issue by SirNerdBear** [csga5000/tinymce-prevent-delete#2]
Thanks for this plugin! Save me time in my project.

I noticed a bug. Say I have a paragraph and inside the paragraph, I have a mceNonEditable span at the end. With the current code, if you put the cursor at the very end fo the paragraph, it won't let you press enter to start a new paragraph, even though this wouldn't affect the span.

I believe this is caused by **this.check** code. It calls **this.checkChildren** to see if any children have _mceNonEditable_. The problem is, this is reversed logic. It makes the p element return as _mceNonEditable_ just because it has an inline span that is mceNonEditable as a child. 

TinyMCE doesn't support nesting editable components so at whatever element you set mceNonEditable on, all children are non-editable. The code should therefore check parents, that way if say a <strong> element was inside the <span class="mceNonEditable"> it would still prevent a delete.

**Comment by csga5000** [comment]
I'll have a look at this.  But I'm pretty sure the issue isn't as simple as you think.  If the code determines that the current element may be deleted and the current element has non-deletable children then the event should be canceled so the entire element (and it's children) are not deleted.

**Comment by SirNerdBear** [comment]
You're correct. If I get the chance today I'll work on updating the code to work with both situations.

**Comment by csga5000** [comment]
I merged your changes, and changed some formatting.  The spacing was a bit odd and such.

I was mildly concerned that this may make it possible to delete a element which has children that are non-editable, but this may not be an issue because of tinymce.

I also somehow managed to produce a quirk while testing. (It's an annoying issue to solve, since the current selection and such can be rather inconsistent.)

But hopefully this increases the plugins reliability.
